export  const colors= [
{color:"IndianRed"},
{color:"LightCoral"},
{color:"Salmon"},
{color:"DarkSalmon"},
{color:"LightSalmon"},
{color:"Crimson"},
{color:"Red"},
{color:"FireBrick"},
{color:"DarkRed"},

{color:"Aqua"},
{color:"Cyan"},
{color:"LightCyan"},
{color:"PaleTurquoise"},
{color:"Aquamarine"},
{color:"Turquoise"},
{color:"MediumTurquoise"},
{color:"DarkTurquoise"},
{color:"CadetBlue"},
{color:"SteelBlue"},

{color:"GreenYellow"},
{color:"Chartreuse"},
{color:"LawnGreen"},
{color:"Lime"},
{color:"LimeGreen"},
{color:"PaleGreen"},
{color:"LightGreen"},
{color:"MediumSpringGreen"},
{color:"SpringGreen"},
{color:"green"},

{color:"Lavender"},
{color:"Thistle"},
{color:"Plum"},
{color:"Violet"},
{color:"Orchid"},
{color:"Fuchsia"},
{color:"Magenta"},
{color:"lime"},
{color:"MediumOrchid"},
{color:"MediumPurple"},
{color:"Purple"},

{color:"Gold"},
{color:"Yellow"},
{color:"LightYellow"},
{color:"LemonChiffon"},
{color:"LightGoldenrodYellow"},
{color:"PapayaWhip"},
{color:"Moccasin"},

{color:"Gray"},
{color:"Silver"},
{color:"White"},

{color:"Black"},
]


